services:
  - type: web
    name: mb-1shot-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
      - backend/**
      ignoredPaths:
      - frontend/**
      - src/** 